// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvHaUbxR-t-wTen9IkhRxmbqS96Lluxs',
    appId: '1:767368546303:web:ea2456af6f34377ff1c9ca',
    messagingSenderId: '767368546303',
    projectId: 'uselessapp-553d3',
    authDomain: 'uselessapp-553d3.firebaseapp.com',
    storageBucket: 'uselessapp-553d3.firebasestorage.app',
    measurementId: 'G-B1Z32JVL6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtwJxLoRHCnuVBVTeiHdleSsjwQbkg2M',
    appId: '1:767368546303:android:82215d2d2463c448f1c9ca',
    messagingSenderId: '767368546303',
    projectId: 'uselessapp-553d3',
    storageBucket: 'uselessapp-553d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5SaGi7dBmogys1ZqQrrKFDgoIOTprfg',
    appId: '1:767368546303:ios:44a77420ccfb0347f1c9ca',
    messagingSenderId: '767368546303',
    projectId: 'uselessapp-553d3',
    storageBucket: 'uselessapp-553d3.firebasestorage.app',
    iosBundleId: 'com.example.uselessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5SaGi7dBmogys1ZqQrrKFDgoIOTprfg',
    appId: '1:767368546303:ios:44a77420ccfb0347f1c9ca',
    messagingSenderId: '767368546303',
    projectId: 'uselessapp-553d3',
    storageBucket: 'uselessapp-553d3.firebasestorage.app',
    iosBundleId: 'com.example.uselessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvHaUbxR-t-wTen9IkhRxmbqS96Lluxs',
    appId: '1:767368546303:web:dc514f1695390d1df1c9ca',
    messagingSenderId: '767368546303',
    projectId: 'uselessapp-553d3',
    authDomain: 'uselessapp-553d3.firebaseapp.com',
    storageBucket: 'uselessapp-553d3.firebasestorage.app',
    measurementId: 'G-X2KW2D48J1',
  );
}
